name: build-binary-action
on:
  push:
    tags:
      - v*
jobs:
  build-linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sh build-clang.sh
      - name: Upload Artifact[linux-clang-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: telegram-bot-api-linux-clang-build-x64
          path: telegram-bot-api/bin/
      - name: Generate Zip
        run: |
          sudo apt-get install zip
          zip -9 telegram-bot-api-linux-clang-build-x64.zip telegram-bot-api/bin/*
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # 上传网址，无需改动
          asset_path: telegram-bot-api-linux-clang-build-x64.zip # 上传路径
          asset_name: telegram-bot-api-linux-clang-build-x64.zip # 资源名
          asset_content_type: application/zip
  build-linux-gpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sh build-g++.sh
      - name: Upload Artifact[linux-g++-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: telegram-bot-api-linux-g++-build-x64
          path: telegram-bot-api/bin/
      - name: Generate Zip
        run: |
          sudo apt-get install zip
          zip -9 telegram-bot-api-linux-g++-build-x64.zip telegram-bot-api/bin/*
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # 上传网址，无需改动
          asset_path: telegram-bot-api-linux-g++-build-x64.zip # 上传路径
          asset_name: telegram-bot-api-linux-g++-build-x64.zip # 资源名
          asset_content_type: application/zip
  build-windows-x64:
    runs-on: windows-latest
    steps:
      - uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: x64
      - uses: actions/checkout@v3
      - name: Build
        run: .\build-windows-x64.ps1
        shell: powershell
      - name: Upload Artifact[Windows-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: telegram-bot-api-Windows-msvc-build-x64
          path: telegram-bot-api\bin\
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # 上传网址，无需改动
          asset_path: telegram-bot-api-windows-x64.zip # 上传路径
          asset_name: telegram-bot-api-windows-x64.zip # 资源名
          asset_content_type: application/zip
  build-windows-x86:
    runs-on: windows-latest
    steps:
      - uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: x86
      - uses: actions/checkout@v3
      - name: Build
        run: .\build-windows-x86.ps1
        shell: powershell
      - name: Upload Artifact[Windows-x86]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: telegram-bot-api-Windows-msvc-build-x86
          path: telegram-bot-api\bin\
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # 上传网址，无需改动
          asset_path: telegram-bot-api-windows-x86.zip # 上传路径
          asset_name: telegram-bot-api-windows-x86.zip # 资源名
          asset_content_type: application/zip
  build-macos-intel:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v3
    - run: sh build-macos-intel.sh
    - name: Upload Artifact[macos-intel]
      uses: actions/upload-artifact@v1.0.0
      with:
        name: telegram-bot-api-macos-build-intel
        path: telegram-bot-api/bin/
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # 上传网址，无需改动
        asset_path: telegram-bot-api-macos-intel.zip # 上传路径
        asset_name: telegram-bot-api-macos-intel.zip # 资源名
        asset_content_type: application/zip
  build-freebsd-bin:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Build in FreeBSD
      id: build
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        mem: 4096
        prepare: |
          pkg install -y curl
          pkg upgrade  -y
          pkg install  -y git
          pkg install  -y gperf
          pkg install  -y cmake
          pkg install  -y zip
        run: |
          sh ./build-freebsd.csh
    - name: Upload Artifact[free-bsd]
      uses: actions/upload-artifact@v1.0.0
      with:
        name: telegram-bot-api-free-bsd
        path: telegram-bot-api/bin/
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # 上传网址，无需改动
        asset_path: telegram-bot-api-freebsd-build.zip # 上传路径
        asset_name: telegram-bot-api-freebsd-build.zip # 资源名
        asset_content_type: application/zip
  build-openbsd-bin:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Build in OpenBSD
      id: build
      uses: vmactions/openbsd-vm@v0
      with:
        usesh: true
        mem: 4096
        prepare: |
          pkg_add -z git gperf php-7.2.10 cmake
        run: |
          sh ./build-openbsd.ksh
    - name: Upload Artifact[open-bsd]
      uses: actions/upload-artifact@v1.0.0
      with:
        name: telegram-bot-api-open-bsd
        path: telegram-bot-api/bin/
    - name: Archive Artifacts
      uses: thedoctor0/zip-release@master
      with:
        type: "zip"
        filename: telegram-bot-api-openbsd.zip
        path: telegram-bot-api/bin/
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "telegram-bot-api-openbsd.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
  build-netbsd-bin:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Build in netbsd
      id: build
      uses: vmactions/netbsd-vm@v0
      with:
        usesh: true
        mem: 4096
        prepare: |
          export PKG_PATH=https://ftp.netbsd.org//pub/pkgsrc/packages/NetBSD/x86_64/9.2/All/
          pkg_add git gperf cmake openssl gcc12-libs
        run: |
          sh ./build-netbsd.sh
    - name: Upload Artifact[net-bsd]
      uses: actions/upload-artifact@v1.0.0
      with:
        name: telegram-bot-api-net-bsd
        path: telegram-bot-api/bin/
    - name: Archive Artifacts
      uses: thedoctor0/zip-release@master
      with:
        type: "zip"
        filename: telegram-bot-api-netbsd.zip
        path: telegram-bot-api/bin/
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "telegram-bot-api-netbsd.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
