name: build-binary-test-action
on: [push]
jobs:
  build-macos-m1:
    runs-on: [macos, arm64]
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v3
    - run: sh build-macos-m1.sh
    - name: Upload Artifact[macos-m1]
      uses: actions/upload-artifact@v1.0.0
      with:
        name: telegram-bot-api-macos-build-m1
        path: telegram-bot-api/bin/
