name: build-linux-action
on: [push]
jobs:
  build-linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sh build-clang.sh
      - name: Upload Artifact[linux-clang-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: telegram-bot-api-linux-clang-build-x64
          path: telegram-bot-api/bin/
  build-linux-gpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sh build-g++.sh
      - name: Upload Artifact[linux-g++-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: telegram-bot-api-linux-g++-build-x64
          path: telegram-bot-api/bin/
  build-windows-x64:
    runs-on: windows-latest
    steps:
      - uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: x64
      - uses: actions/checkout@v3
      - name: Build
        run: .\build-windows-x64.ps1
        shell: powershell
      - name: Upload Artifact[Windows-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: telegram-bot-api-Windows-msvc-build-x64
          path: telegram-bot-api\bin\
  build-windows-x86:
    runs-on: windows-latest
    steps:
      - uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: x86
      - uses: actions/checkout@v3
      - name: Build
        run: .\build-windows-x86.ps1
        shell: powershell
      - name: Upload Artifact[Windows-x86]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: telegram-bot-api-Windows-msvc-build-x86
          path: telegram-bot-api\bin\