name: build-binary-test-action
on:
  push:
    tags:
      - test*
jobs:
  # build-macos-m1:
  #   runs-on: [macos, arm64]
  #   steps:
  #   - uses: maxim-lobanov/setup-xcode@v1
  #     with:
  #       xcode-version: latest-stable
  #   - uses: actions/checkout@v3
  #   - run: sh build-macos-m1.sh
  #   - name: Upload Artifact[macos-m1]
  #     uses: actions/upload-artifact@v1.0.0
  #     with:
  #       name: telegram-bot-api-macos-build-m1
  #       path: telegram-bot-api/bin/
  #   - name: Archive Artifacts
  #     uses: thedoctor0/zip-release@master
  #     with:
  #       type: "zip"
  #       filename: AppName-${{github.ref_name}}-windows.zip
  #       directory: build/windows/runner/Release
  # build-openbsd-bin:
  #   runs-on: macos-12
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build in OpenBSD
  #     id: build
  #     uses: vmactions/openbsd-vm@v0
  #     with:
  #       usesh: true
  #       mem: 4096
  #       prepare: |
  #         pkg_add -z git gperf php-7.2.10 cmake
  #       run: |
  #         sh ./build-openbsd.ksh
  #   - name: Upload Artifact[open-bsd]
  #     uses: actions/upload-artifact@v1.0.0
  #     with:
  #       name: telegram-bot-api-open-bsd
  #       path: telegram-bot-api/bin/
  #   - name: Archive Artifacts
  #     uses: thedoctor0/zip-release@master
  #     with:
  #       type: "zip"
  #       filename: telegram-bot-api-${{github.ref_name}}-openbsd.zip
  #       directory: telegram-bot-api/bin/
  #   - name: Create Release
  #     id: create_release
  #     uses: ncipollo/release-action@v1
  #     with:
  #       artifacts: "telegram-bot-api-${{github.ref_name}}-openbsd.zip"
  #       token: ${{ secrets.GITHUB_TOKEN }}
  #       allowUpdates: true
  build-netbsd-bin:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Build in netbsd
      id: build
      uses: vmactions/netbsd-vm@v0
      with:
        usesh: true
        mem: 4096
        prepare: |
          export PKG_PATH=https://ftp.netbsd.org//pub/pkgsrc/packages/NetBSD/x86_64/9.2/All/
          pkg_add git gperf cmake openssl gcc5-libs
        run: |
          sh ./build-netbsd.sh
    - name: Upload Artifact[net-bsd]
      uses: actions/upload-artifact@v1.0.0
      with:
        name: telegram-bot-api-net-bsd
        path: telegram-bot-api/bin/
    - name: Archive Artifacts
      uses: thedoctor0/zip-release@master
      with:
        type: "zip"
        filename: telegram-bot-api-${{github.ref_name}}-netbsd.zip
        directory: telegram-bot-api/bin/
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "telegram-bot-api-${{github.ref_name}}-netbsd.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
