name: build-linux-action
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    - name: Set up Clang
    uses: egor-tensin/setup-clang@v1
    with:
      version: 14
      platform: x64
    steps:
      - uses: actions/checkout@v3
      - run: sh build.sh